packages:
  - .

allowBuilds:
  esbuild: false
  sharp: false
  unrs-resolver: false

minimumReleaseAge: 10080 # 7 days in minutes
minimumReleaseAgeExclude:
  - pnpm@12.10.1

  - next@16.4.0
  - eslint-config-next@16.4.0
  - '@next/eslint-plugin-next@16.4.0'
  - '@next/env@16.4.0'
  - '@next/swc-darwin-arm64@16.4.0'
  - '@next/swc-darwin-x64@16.4.0'
  - '@next/swc-linux-arm64-gnu@16.4.0'
  - '@next/swc-linux-arm64-musl@16.4.0'
  - '@next/swc-linux-x64-gnu@16.4.0'
  - '@next/swc-linux-x64-musl@16.4.0'
  - '@next/swc-win32-arm64-msvc@16.4.0'
  - '@next/swc-win32-x64-msvc@16.4.0'
  - '@next/mdx@16.4.0'

overrides:
  chokidar: '>=5'
  jose: '>=6'
  semver: '>=7'
  uuid@<14.0.0: ^14.0.0

trustPolicy: no-downgrade
