allowBuilds:
  sharp: false
  unrs-resolver: false

autoInstallPeers: false

enablePrePostScripts: true

onlyBuiltDependencies:
  - sharp
  - unrs-resolver

overrides:
  eslint: ^9
  postcss@<8.5.10: '>=8.5.10'
  uuid@<14.0.0: '>=14.0.0'
