autoInstallPeers: true

enablePrePostScripts: true

onlyBuiltDependencies:
  - sharp
  - unrs-resolver

overrides:
  eslint: '^9'
  '@eslint/js': '^9'
  '@stylistic/eslint-plugin': '>=5.0.0'
  '@types/node': '^24'
