name: Build and Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
    - main

  workflow_dispatch: null
jobs:
  test:
    runs-on: ubuntu-26.04-arm
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false

    - uses: pnpm/setup@v3
      name: Install pnpm
      with:
        install: false

    - name: Install dependencies
      run: pnpm install --no-frozen-lockfile

    - name: Build
      run: pnpm all
