name: Build and Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
    - main

  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        node-version: [22.x]

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v5
      with:
        node-version: ${{ matrix.node-version }}
        check-latest: true
        package-manager-cache: false

    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        run_install: |
          - recursive: true
            args: [--frozen-lockfile]


    - name: Build
      run: pnpm all

  configure:

    permissions:
      id-token: write
      pull-requests: write
      statuses: write
      contents: write

    runs-on: ubuntu-latest

    if: github.actor != 'dependabot[bot]'

    steps:
    - name: Pull request auto merge enabler
      if: github.event_name == 'pull_request'
      uses: poad/github-pull-request-auto-merge-enable-action@v3
      with:
        pull_request_number: ${{ github.event.pull_request.number }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ github.event.repository.name }}
        owner: ${{ github.repository_owner }}
        merge_method: SQUASH
