name: Build and Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
    - main

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Use Node.js
      uses: actions/setup-node@v5
      with:
        node-version: 'lts/*'
        check-latest: true
        package-manager-cache: false

    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        run_install: |
          - recursive: true
            args: [--frozen-lockfile]

    - name: Build
      run: pnpm all

  configure:

    permissions:
      pull-requests: write
      contents: write

    runs-on: ubuntu-latest

    # リポジトリオーナーの Pull Request はドラフト以外は自動マージを有効にする
    if: ${{ github.event.pull_request.draft == false && (github.actor != 'dependabot[bot]' || github.repository_owner == github.actor) }}

    steps:
      - name: Enable auto-merge for Pull Request
        run: |
          gh pr review --approve "$PR_URL"
          gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

